services:
  postgres:
    container_name: rr-postgres
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=repo_radar
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
