apiVersion: v1
data:
  GITHUB_TOKEN: Z2hwX0JJT1FuUzJ0OUtkOVowTE9OazRacTRGaFhSY2hvRTJET0lhNA==
  OPENSHIFT_TOKEN: ""
  POSTGRES_PASSWORD: cG9zdGdyZXM=
kind: Secret
metadata:
  name: repo-radar-secrets
  namespace: default
type: Opaque
