apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: repo-radar-cluster-pods-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns"]
  verbs: ["get", "list", "watch"]