apiVersion: v1
automountServiceAccountToken: true
imagePullSecrets:
- name: repo-radar-backend-sa-dockercfg-4phgk
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: repo-radar-backend
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2025-03-19T18:08:42Z"
  labels:
    app.kubernetes.io/instance: repo-radar-backend
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: repo-radar-backend
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: qnnp-services-0.1.0
  name: repo-radar-backend-sa
  namespace: default
  resourceVersion: "452048333"
  uid: a180f675-3f8d-4558-bb87-f5855042acba
secrets:
- name: repo-radar-backend-sa-dockercfg-4phgk
